Repository SOPT-all/35-APPJAM-SERVER-GONGBAEK, pull requests merged in 2025-01, with the labels that each got.

#9 [init] #8 response setting
  src/main/java/com/ggang/be/api/common/ApiResponse.java
  src/main/java/com/ggang/be/api/common/PracticeController.java
  src/main/java/com/ggang/be/api/common/ResponseBuilder.java
  src/main/java/com/ggang/be/api/common/ResponseError.java
  src/main/java/com/ggang/be/api/common/ResponseSuccess.java
  src/main/java/com/ggang/be/api/exception/GlobalExceptionHandler.java
Labels: :fist_right: init

#12 [init] #11 ResponseCode 설정
  src/main/java/com/ggang/be/api/common/ResponseError.java
  src/main/java/com/ggang/be/api/common/ResponseSuccess.java
Labels: :fist_right: init

#13 [init] #10 entity 초기 세팅
  build.gradle
  src/main/java/com/ggang/be/Application.java
  src/main/java/com/ggang/be/api/common/HealthController.java
  src/main/java/com/ggang/be/domain/BaseTimeEntity.java
  src/main/java/com/ggang/be/domain/advertisement/AdvertisementEntity.java
  src/main/java/com/ggang/be/domain/comment/CommentEntity.java
  src/main/java/com/ggang/be/domain/constant/Category.java
  src/main/java/com/ggang/be/domain/constant/Gender.java
  src/main/java/com/ggang/be/domain/constant/Mbti.java
  src/main/java/com/ggang/be/domain/constant/Status.java
  src/main/java/com/ggang/be/domain/constant/WeekDate.java
  src/main/java/com/ggang/be/domain/everyGroup/EveryGroupEntity.java
  src/main/java/com/ggang/be/domain/gongbaekTimeTable/GongbaekTimeTableEntity.java
  src/main/java/com/ggang/be/domain/lectureTimeTable/LectureTimeTableEntity.java
  src/main/java/com/ggang/be/domain/onceGroup/OnceGroupEntity.java
  src/main/java/com/ggang/be/domain/school/SchoolEntity.java
  src/main/java/com/ggang/be/domain/schoolMajor/SchoolMajorEntity.java
  src/main/java/com/ggang/be/domain/user/UserEntity.java
  src/main/java/com/ggang/be/domain/userEveryGroup/UserEveryGroupEntity.java
  src/main/java/com/ggang/be/domain/userOnceGroup/UserOnceGroupEntity.java
Labels: :fist_right: init

#17 [refactor] #15 MongoDB -> RDB 형태로 변환하는 형태로 엔티티 수정
  build.gradle
  src/main/java/com/ggang/be/domain/gongbaekTimeSlot/GongbaekTimeSlotEntity.java
  src/main/java/com/ggang/be/domain/gongbaekTimeTable/GongbaekTimeTableEntity.java
  src/main/java/com/ggang/be/domain/lectureTimeTable/LectureTimeSlotEntity.java
  src/main/java/com/ggang/be/domain/lectureTimeTable/LectureTimeTableEntity.java
  src/main/java/com/ggang/be/domain/schoolMajor/SchoolMajorEntity.java
  src/main/java/com/ggang/be/domain/user/UserEntity.java
Labels: :factory: refactor

#23 [init] .gitkeep을 통하여 패키지 구조 공통으로 보이도록 하기
  src/main/java/com/ggang/be/api/advertisement/controller/.gitkeep
  src/main/java/com/ggang/be/api/comment/controller/.gitkeep
  src/main/java/com/ggang/be/api/everyGroup/controller/.gitkeep
  src/main/java/com/ggang/be/api/facade/.gitkeep
  src/main/java/com/ggang/be/api/gongbaekTimeSlot/controller/.gitkeep
  src/main/java/com/ggang/be/api/lectureTimeSlot/controller/.gitkeep
  src/main/java/com/ggang/be/api/onceGroup/controller/.gitkeep
  src/main/java/com/ggang/be/api/school/controller/.gitkeep
  src/main/java/com/ggang/be/api/schoolMajor/controller/.gitkeep
  src/main/java/com/ggang/be/api/user/controller/.gitkeep
  src/main/java/com/ggang/be/domain/advertisement/application/.gitkeep
  src/main/java/com/ggang/be/domain/advertisement/infra/.gitkeep
  src/main/java/com/ggang/be/domain/comment/application/.gitkeep
  src/main/java/com/ggang/be/domain/comment/infra/.gitkeep
  src/main/java/com/ggang/be/domain/everyGroup/application/.gitkeep
  src/main/java/com/ggang/be/domain/everyGroup/infra/.gitkeep
  src/main/java/com/ggang/be/domain/gongbaekTimeSlot/application/.gitkeep
  src/main/java/com/ggang/be/domain/gongbaekTimeSlot/infra/.gitkeep
  src/main/java/com/ggang/be/domain/lectureTimeSlot/LectureTimeSlotEntity.java
  src/main/java/com/ggang/be/domain/lectureTimeSlot/application/.gitkeep
  src/main/java/com/ggang/be/domain/lectureTimeSlot/infra/.gitkeep
  src/main/java/com/ggang/be/domain/onceGroup/application/.gitkeep
  src/main/java/com/ggang/be/domain/onceGroup/infra/.gitkeep
  src/main/java/com/ggang/be/domain/school/application/.gitkeep
  src/main/java/com/ggang/be/domain/school/infra/.gitkeep
  src/main/java/com/ggang/be/domain/schoolMajor/application/.gitkeep
  src/main/java/com/ggang/be/domain/schoolMajor/infra/.gitkeep
  src/main/java/com/ggang/be/domain/user/UserEntity.java
  src/main/java/com/ggang/be/domain/user/application/.gitkeep
  src/main/java/com/ggang/be/domain/user/infra/.gitkeep
  src/main/java/com/ggang/be/domain/userEveryGroup/application/.gitkeep
  src/main/java/com/ggang/be/domain/userEveryGroup/infra/.gitkeep
  src/main/java/com/ggang/be/domain/userOnceGroup/application/.gitkeep
  src/main/java/com/ggang/be/domain/userOnceGroup/infra/.gitkeep
  src/main/java/com/ggang/be/global/config/.gitkeep
  src/main/java/com/ggang/be/global/exception/.gitkeep
Labels: :fist_right: init

#20 [init] #16 GlobalExceptionHandler 설정
  src/main/java/com/ggang/be/api/common/ApiResponse.java
  src/main/java/com/ggang/be/api/common/PracticeController.java
  src/main/java/com/ggang/be/api/common/ResponseBuilder.java
  src/main/java/com/ggang/be/api/common/ResponseError.java
  src/main/java/com/ggang/be/api/exception/GlobalExceptionHandler.java
  src/main/java/com/ggang/be/api/exception/GongBaekException.java
Labels: :star: feat, :fist_right: init

#24 [feat] 소개글 검증 API 기능 개발
  src/main/java/com/ggang/be/api/common/ApiResponse.java
  src/main/java/com/ggang/be/api/common/ResponseError.java
  src/main/java/com/ggang/be/api/user/controller/.gitkeep
  src/main/java/com/ggang/be/api/user/controller/UserController.java
  src/main/java/com/ggang/be/api/user/dto/ValidIntroductionRequestDto.java
  src/main/java/com/ggang/be/global/util/LengthValidator.java
  src/test/java/com/ggang/be/ApplicationTests.java
  src/test/java/com/ggang/be/global/util/LengthValidatorTest.java
Labels: :star: feat

#27 [feat] 학교 검색 api 구현 진행
  src/main/java/com/ggang/be/api/facade/.gitkeep
  src/main/java/com/ggang/be/api/facade/SearchSchoolFacade.java
  src/main/java/com/ggang/be/api/school/controller/.gitkeep
  src/main/java/com/ggang/be/api/school/controller/SchoolController.java
  src/main/java/com/ggang/be/api/school/dto/SchoolSearchResponse.java
  src/main/java/com/ggang/be/api/school/service/SchoolService.java
  src/main/java/com/ggang/be/domain/school/SchoolEntity.java
  src/main/java/com/ggang/be/domain/school/application/.gitkeep
  src/main/java/com/ggang/be/domain/school/application/SchoolServiceImpl.java
  src/main/java/com/ggang/be/domain/school/dto/SchoolSearchVo.java
  src/main/java/com/ggang/be/domain/school/infra/.gitkeep
  src/main/java/com/ggang/be/domain/school/infra/SchoolRepository.java
  src/main/java/com/ggang/be/global/annotation/Facade.java
  src/test/java/com/ggang/be/domain/school/application/SchoolServiceImplTest.java
Labels: :star: feat

#32 [feat] 닉네임 검증 api 구현 진행
  src/main/java/com/ggang/be/api/common/ResponseError.java
  src/main/java/com/ggang/be/api/facade/SignupFacade.java
  src/main/java/com/ggang/be/api/user/NicknameValidator.java
  src/main/java/com/ggang/be/api/user/controller/UserController.java
  src/main/java/com/ggang/be/api/user/service/UserService.java
  src/main/java/com/ggang/be/domain/user/UserEntity.java
  src/main/java/com/ggang/be/domain/user/application/UserServiceImpl.java
  src/main/java/com/ggang/be/domain/user/infra/UserRepository.java
  src/test/java/com/ggang/be/api/user/NicknameValidatorTest.java
  src/test/java/com/ggang/be/domain/user/application/UserServiceImplTest.java
Labels: :star: feat, :factory: refactor

#37 [feat] 나의 학교명 조회 API 기능 구현
  src/main/java/com/ggang/be/api/user/controller/UserController.java
  src/main/java/com/ggang/be/api/user/dto/UserSchoolResponseDto.java
  src/main/java/com/ggang/be/api/user/service/UserService.java
  src/main/java/com/ggang/be/domain/user/UserEntity.java
  src/main/java/com/ggang/be/domain/user/application/UserServiceImpl.java
  src/main/java/com/ggang/be/domain/user/dto/UserDto.java
  src/main/java/com/ggang/be/domain/user/dto/UserSchoolDto.java
  src/main/java/com/ggang/be/domain/user/infra/UserRepository.java
  src/main/java/com/ggang/be/domain/userEveryGroup/UserEveryGroupEntity.java
  src/main/java/com/ggang/be/domain/userOnceGroup/UserOnceGroupEntity.java
Labels: :star: feat

#38 [feat] 회원가입 api 구현하기
  build.gradle
  src/main/java/com/ggang/be/api/facade/SignupFacade.java
  src/main/java/com/ggang/be/api/lectureTimeSlot/service/LectureTimeSlotService.java
  src/main/java/com/ggang/be/api/school/service/SchoolService.java
  src/main/java/com/ggang/be/api/user/controller/UserController.java
  src/main/java/com/ggang/be/api/user/dto/SignupRequest.java
  src/main/java/com/ggang/be/api/user/dto/SignupResponse.java
  src/main/java/com/ggang/be/api/user/dto/ValidIntroductionRequest.java
  src/main/java/com/ggang/be/api/user/dto/ValidIntroductionRequestDto.java
  src/main/java/com/ggang/be/api/user/service/UserService.java
  src/main/java/com/ggang/be/api/user/vo/TimeTableVo.java
  src/main/java/com/ggang/be/domain/lectureTimeSlot/LectureTimeSlotEntity.java
  src/main/java/com/ggang/be/domain/lectureTimeSlot/application/.gitkeep
  src/main/java/com/ggang/be/domain/lectureTimeSlot/application/LectureTimeSlotServiceImpl.java
  src/main/java/com/ggang/be/domain/lectureTimeSlot/infra/.gitkeep
  src/main/java/com/ggang/be/domain/lectureTimeSlot/infra/LectureTimeSlotRepository.java
  src/main/java/com/ggang/be/domain/lectureTimeSlot/vo/LectureTimeSlotVo.java
  src/main/java/com/ggang/be/domain/school/SchoolEntity.java
  src/main/java/com/ggang/be/domain/school/application/SchoolServiceImpl.java
  src/main/java/com/ggang/be/domain/user/UserEntity.java
  src/main/java/com/ggang/be/domain/user/application/UserServiceImpl.java
  src/main/java/com/ggang/be/domain/user/dto/SaveUserSignUp.java
  src/main/java/com/ggang/be/global/jwt/JwtProperties.java
  src/main/java/com/ggang/be/global/jwt/JwtService.java
  src/test/java/com/ggang/be/domain/lectureTimeSlot/application/LectureTimeSlotServiceImplTest.java
  src/test/java/com/ggang/be/domain/school/application/SchoolServiceImplTest.java
  src/test/java/com/ggang/be/domain/user/application/UserServiceImplTest.java
  src/test/java/com/ggang/be/global/jwt/JwtServiceTest.java
Labels: :star: feat

#39 [feat] 등록자 프로필 조회 API 기능 구현
  src/main/java/com/ggang/be/api/facade/GroupFacade.java
  src/main/java/com/ggang/be/api/group/controller/GroupController.java
  src/main/java/com/ggang/be/api/group/dto/GroupUserInfoResponseDto.java
  src/main/java/com/ggang/be/api/group/everyGroup/service/EveryGroupService.java
  src/main/java/com/ggang/be/api/group/onceGroup/service/OnceGroupService.java
  src/main/java/com/ggang/be/api/user/service/UserService.java
  src/main/java/com/ggang/be/domain/everyGroup/application/EveryGroupServiceImpl.java
  src/main/java/com/ggang/be/domain/onceGroup/application/OnceGroupServiceImpl.java
  src/main/java/com/ggang/be/domain/user/application/UserService.java
  src/main/java/com/ggang/be/domain/user/application/UserServiceImpl.java
  src/main/java/com/ggang/be/domain/user/dto/UserInfo.java
Labels: :star: feat

#42 [feat] 댓글 작성 api 구현
  src/main/java/com/ggang/be/api/comment/controller/.gitkeep
  src/main/java/com/ggang/be/api/comment/controller/CommentController.java
  src/main/java/com/ggang/be/api/comment/dto/WriteCommentRequest.java
  src/main/java/com/ggang/be/api/comment/dto/WriteCommentResponse.java
  src/main/java/com/ggang/be/api/comment/service/CommentService.java
  src/main/java/com/ggang/be/api/exception/GlobalExceptionHandler.java
  src/main/java/com/ggang/be/api/facade/CommentFacade.java
  src/main/java/com/ggang/be/api/group/everyGroup/service/EveryGroupService.java
  src/main/java/com/ggang/be/api/group/onceGroup/service/OnceGroupService.java
  src/main/java/com/ggang/be/domain/comment/CommentEntity.java
  src/main/java/com/ggang/be/domain/comment/application/.gitkeep
  src/main/java/com/ggang/be/domain/comment/application/CommentServiceImpl.java
  src/main/java/com/ggang/be/domain/comment/infra/.gitkeep
  src/main/java/com/ggang/be/domain/comment/infra/CommentRepository.java
  src/main/java/com/ggang/be/domain/everyGroup/EveryGroupEntity.java
  src/main/java/com/ggang/be/domain/everyGroup/application/EveryGroupServiceImpl.java
  src/main/java/com/ggang/be/domain/onceGroup/OnceGroupEntity.java
  src/main/java/com/ggang/be/domain/onceGroup/application/OnceGroupServiceImpl.java
  src/main/java/com/ggang/be/domain/user/UserEntity.java
  src/main/java/com/ggang/be/global/jwt/JwtService.java
  src/test/java/com/ggang/be/domain/comment/CommentFixture.java
  src/test/java/com/ggang/be/domain/everyGroup/EveryGroupFixture.java
  src/test/java/com/ggang/be/domain/everyGroup/application/EveryGroupServiceImplTest.java
  src/test/java/com/ggang/be/domain/onceGroup/OnceGroupFixture.java
  src/test/java/com/ggang/be/domain/onceGroup/application/OnceGroupServiceImplTest.java
Labels: :star: feat

#49 [feat] 나의 모임 전체 조회 API 기능 구현
  src/main/java/com/ggang/be/api/facade/GroupFacade.java
  src/main/java/com/ggang/be/api/group/controller/GroupController.java
  src/main/java/com/ggang/be/api/group/dto/FillGroupFilterRequest.java
  src/main/java/com/ggang/be/api/group/dto/GroupRequestDto.java
  src/main/java/com/ggang/be/api/group/dto/GroupResponse.java
  src/main/java/com/ggang/be/api/group/everyGroup/service/EveryGroupService.java
  src/main/java/com/ggang/be/api/group/onceGroup/service/OnceGroupService.java
  src/main/java/com/ggang/be/api/mapper/GroupResponseMapper.java
  src/main/java/com/ggang/be/api/userEveryGroup/service/UserEveryGroupService.java
  src/main/java/com/ggang/be/api/userOnceGroup/service/UserOnceGroupService.java
  src/main/java/com/ggang/be/domain/constant/FillGroupType.java
  src/main/java/com/ggang/be/domain/constant/Status.java
  src/main/java/com/ggang/be/domain/group/GroupVoMaker.java
  src/main/java/com/ggang/be/domain/group/dto/GroupVo.java
  src/main/java/com/ggang/be/domain/group/dto/ReadGroup.java
  src/main/java/com/ggang/be/domain/group/everyGroup/application/EveryGroupServiceImpl.java
  src/main/java/com/ggang/be/domain/group/everyGroup/dto/EveryGroupDetail.java
  src/main/java/com/ggang/be/domain/group/everyGroup/dto/EveryGroupVo.java
  src/main/java/com/ggang/be/domain/group/everyGroup/dto/ReadEveryGroup.java
  src/main/java/com/ggang/be/domain/group/everyGroup/infra/EveryGroupRepository.java
  src/main/java/com/ggang/be/domain/group/onceGroup/OnceGroupEntity.java
  src/main/java/com/ggang/be/domain/group/onceGroup/application/OnceGroupServiceImpl.java
  src/main/java/com/ggang/be/domain/group/onceGroup/dto/OnceGroupVo.java
  src/main/java/com/ggang/be/domain/group/onceGroup/dto/ReadOnceGroup.java
  src/main/java/com/ggang/be/domain/group/onceGroup/infra/.gitkeep
  src/main/java/com/ggang/be/domain/group/onceGroup/infra/OnceGroupRepository.java
  src/main/java/com/ggang/be/domain/userEveryGroup/application/.gitkeep
  src/main/java/com/ggang/be/domain/userEveryGroup/application/UserEveryGroupImpl.java
  src/main/java/com/ggang/be/domain/userEveryGroup/infra/.gitkeep
  src/main/java/com/ggang/be/domain/userEveryGroup/infra/UserEveryGroupRepository.java
  src/main/java/com/ggang/be/domain/userOnceGroup/application/.gitkeep
  src/main/java/com/ggang/be/domain/userOnceGroup/application/UserOnceGroupImpl.java
  src/main/java/com/ggang/be/domain/userOnceGroup/infra/.gitkeep
  src/main/java/com/ggang/be/domain/userOnceGroup/infra/UserOnceGroupRepository.java
Labels: :star: feat

#45 [feat] 공백채우기 등록하기 api 구현
  docker-compose.yml
  src/main/java/com/ggang/be/api/common/ResponseError.java
  src/main/java/com/ggang/be/api/facade/GongbaekRequestFacade.java
  src/main/java/com/ggang/be/api/facade/GroupFacade.java
  src/main/java/com/ggang/be/api/gongbaekTimeSlot/controller/.gitkeep
  src/main/java/com/ggang/be/api/gongbaekTimeSlot/service/GongbaekTimeSlotService.java
  src/main/java/com/ggang/be/api/group/controller/GroupController.java
  src/main/java/com/ggang/be/api/group/dto/RegisterGongbaekRequest.java
  src/main/java/com/ggang/be/api/group/dto/RegisterGongbaekResponse.java
  src/main/java/com/ggang/be/api/group/everyGroup/service/EveryGroupService.java
  src/main/java/com/ggang/be/api/group/onceGroup/service/OnceGroupService.java
  src/main/java/com/ggang/be/api/lectureTimeSlot/service/LectureTimeSlotService.java
  src/main/java/com/ggang/be/api/mapper/GroupResponseMapper.java
  src/main/java/com/ggang/be/domain/gongbaekTimeSlot/GongbaekTimeSlotEntity.java
  src/main/java/com/ggang/be/domain/gongbaekTimeSlot/application/.gitkeep
  src/main/java/com/ggang/be/domain/gongbaekTimeSlot/application/GongbaekTimeSlotServiceImpl.java
  src/main/java/com/ggang/be/domain/gongbaekTimeSlot/dto/GongbaekTimeSlotRequest.java
  src/main/java/com/ggang/be/domain/gongbaekTimeSlot/infra/.gitkeep
  src/main/java/com/ggang/be/domain/gongbaekTimeSlot/infra/GongbaekTimeSlotRepository.java
  src/main/java/com/ggang/be/domain/group/dto/RegisterGroupServiceRequest.java
  src/main/java/com/ggang/be/domain/group/everyGroup/EveryGroupEntity.java
  src/main/java/com/ggang/be/domain/group/everyGroup/application/EveryGroupServiceImpl.java
  src/main/java/com/ggang/be/domain/group/everyGroup/dto/EveryGroupDetail.java
  src/main/java/com/ggang/be/domain/group/everyGroup/dto/EveryGroupDto.java
  src/main/java/com/ggang/be/domain/group/everyGroup/dto/EveryGroupVo.java
  src/main/java/com/ggang/be/domain/group/everyGroup/infra/EveryGroupRepository.java
  src/main/java/com/ggang/be/domain/group/onceGroup/OnceGroupEntity.java
  src/main/java/com/ggang/be/domain/group/onceGroup/application/OnceGroupServiceImpl.java
  src/main/java/com/ggang/be/domain/group/onceGroup/dto/OnceGroupDto.java
  src/main/java/com/ggang/be/domain/group/onceGroup/dto/OnceGroupVo.java
  src/main/java/com/ggang/be/domain/group/onceGroup/infra/OnceGroupRepository.java
  src/main/java/com/ggang/be/domain/lectureTimeSlot/application/LectureTimeSlotServiceImpl.java
  src/main/java/com/ggang/be/domain/lectureTimeSlot/dto/LectureTimeSlotRequest.java
  src/main/java/com/ggang/be/domain/lectureTimeSlot/infra/LectureTimeSlotRepository.java
  src/main/java/com/ggang/be/global/util/TimeValidator.java
  src/test/java/com/ggang/be/domain/gongbaekTImeSlot/GongbaekTimeSlotFixture.java
  src/test/java/com/ggang/be/domain/group/everyGroup/EveryGroupFixture.java
  src/test/java/com/ggang/be/domain/group/onceGroup/OnceGroupFixture.java
Labels: :star: feat

#52 [feat] 가장 가까운 모임 1개 조회 API 기능 구현
  .gitignore
  src/main/java/com/ggang/be/api/comment/dto/ReadCommentRequest.java
  src/main/java/com/ggang/be/api/comment/dto/WriteCommentRequest.java
  src/main/java/com/ggang/be/api/facade/CommentFacade.java
  src/main/java/com/ggang/be/api/facade/GongbaekRequestFacade.java
  src/main/java/com/ggang/be/api/facade/GroupFacade.java
  src/main/java/com/ggang/be/api/group/controller/GroupController.java
  src/main/java/com/ggang/be/api/group/dto/GroupRequestDto.java
  src/main/java/com/ggang/be/api/group/dto/NearestGroupResponse.java
  src/main/java/com/ggang/be/api/group/dto/ReadFillMembersRequest.java
  src/main/java/com/ggang/be/api/group/dto/RegisterGongbaekRequest.java
  src/main/java/com/ggang/be/api/group/everyGroup/service/UserEveryGroupService.java
  src/main/java/com/ggang/be/api/group/onceGroup/service/UserOnceGroupService.java
  src/main/java/com/ggang/be/api/mapper/GroupResponseMapper.java
  src/main/java/com/ggang/be/api/userEveryGroup/service/UserEveryGroupService.java
  src/main/java/com/ggang/be/api/userOnceGroup/service/UserOnceGroupService.java
  src/main/java/com/ggang/be/domain/constant/GroupType.java
  src/main/java/com/ggang/be/domain/constant/WeekDate.java
  src/main/java/com/ggang/be/domain/group/dto/GroupVo.java
  src/main/java/com/ggang/be/domain/group/dto/RegisterGroupServiceRequest.java
  src/main/java/com/ggang/be/domain/group/everyGroup/dto/EveryGroupVo.java
  src/main/java/com/ggang/be/domain/group/onceGroup/OnceGroupEntity.java
  src/main/java/com/ggang/be/domain/group/onceGroup/application/OnceGroupServiceImpl.java
  src/main/java/com/ggang/be/domain/group/onceGroup/dto/OnceGroupVo.java
  src/main/java/com/ggang/be/domain/group/vo/GroupCommentVo.java
  src/main/java/com/ggang/be/domain/user/application/UserServiceImpl.java
  src/main/java/com/ggang/be/domain/userEveryGroup/application/UserEveryGroupImpl.java
  src/main/java/com/ggang/be/domain/userEveryGroup/application/UserEveryGroupServiceImpl.java
  src/main/java/com/ggang/be/domain/userEveryGroup/dto/NearestEveryGroup.java
  src/main/java/com/ggang/be/domain/userOnceGroup/application/UserOnceGroupImpl.java
  src/main/java/com/ggang/be/domain/userOnceGroup/application/UserOnceGroupServiceImpl.java
  src/main/java/com/ggang/be/domain/userOnceGroup/dto/NearestOnceGroup.java
  src/test/java/com/ggang/be/domain/group/GroupCommentVoFixture.java
Labels: :star: feat

#58 [feat] 채우기 모임 전체 조회 API 기능 구현
  src/main/java/com/ggang/be/api/facade/GongbaekRequestFacade.java
  src/main/java/com/ggang/be/api/facade/GroupFacade.java
  src/main/java/com/ggang/be/api/group/controller/GroupController.java
  src/main/java/com/ggang/be/api/group/dto/ActiveGroupsResponse.java
  src/main/java/com/ggang/be/api/group/dto/GroupRequest.java
  src/main/java/com/ggang/be/api/group/everyGroup/service/EveryGroupService.java
  src/main/java/com/ggang/be/api/group/onceGroup/service/OnceGroupService.java
  src/main/java/com/ggang/be/api/lectureTimeSlot/service/LectureTimeSlotService.java
  src/main/java/com/ggang/be/api/mapper/GroupResponseMapper.java
  src/main/java/com/ggang/be/domain/constant/Status.java
  src/main/java/com/ggang/be/domain/group/everyGroup/application/EveryGroupServiceImpl.java
  src/main/java/com/ggang/be/domain/group/onceGroup/application/OnceGroupServiceImpl.java
  src/main/java/com/ggang/be/domain/group/onceGroup/dto/OnceGroupVo.java
  src/main/java/com/ggang/be/domain/timslot/lectureTimeSlot/application/LectureTimeSlotServiceImpl.java
Labels: :star: feat

#60 [feat] 참여 가능한 모임 조회 API 기능 구현
  src/main/java/com/ggang/be/api/facade/GroupFacade.java
  src/main/java/com/ggang/be/api/group/controller/GroupController.java
  src/main/java/com/ggang/be/domain/timslot/lectureTimeSlot/application/LectureTimeSlotServiceImpl.java
  src/main/java/com/ggang/be/domain/timslot/lectureTimeSlot/infra/LectureTimeSlotRepository.java
Labels: :star: feat

#56 [fix] 댓글 조회 API (모임방 / 채우기) 작성자 관련 boolean 상태 던져줄 수 있도록 수정
  src/main/java/com/ggang/be/api/comment/controller/CommentController.java
  src/main/java/com/ggang/be/api/facade/CommentFacade.java
  src/main/java/com/ggang/be/api/group/everyGroup/service/EveryGroupService.java
  src/main/java/com/ggang/be/api/group/onceGroup/service/OnceGroupService.java
  src/main/java/com/ggang/be/api/userEveryGroup/service/UserEveryGroupService.java
  src/main/java/com/ggang/be/api/userOnceGroup/service/UserOnceGroupService.java
  src/main/java/com/ggang/be/domain/group/GroupCommentVoMaker.java
  src/main/java/com/ggang/be/domain/group/everyGroup/application/EveryGroupServiceImpl.java
  src/main/java/com/ggang/be/domain/group/onceGroup/application/OnceGroupServiceImpl.java
  src/main/java/com/ggang/be/domain/group/vo/GroupCommentVo.java
  src/main/java/com/ggang/be/domain/userEveryGroup/application/UserEveryGroupServiceImpl.java
  src/main/java/com/ggang/be/domain/userOnceGroup/application/UserOnceGroupServiceImpl.java
  src/test/java/com/ggang/be/domain/group/GroupCommentVoFixture.java
  src/test/java/com/ggang/be/domain/group/everyGroup/application/EveryGroupServiceImplTest.java
  src/test/java/com/ggang/be/domain/group/onceGroup/application/OnceGroupServiceImplTest.java
Labels: :star: feat

#64 [feat] 모임 신청 API 기능 구현
  src/main/java/com/ggang/be/api/common/ResponseError.java
  src/main/java/com/ggang/be/api/facade/GroupFacade.java
  src/main/java/com/ggang/be/api/group/controller/GroupController.java
  src/main/java/com/ggang/be/api/group/everyGroup/service/EveryGroupService.java
  src/main/java/com/ggang/be/api/group/onceGroup/service/OnceGroupService.java
  src/main/java/com/ggang/be/api/userEveryGroup/service/UserEveryGroupService.java
  src/main/java/com/ggang/be/api/userOnceGroup/service/UserOnceGroupService.java
  src/main/java/com/ggang/be/domain/group/everyGroup/EveryGroupEntity.java
  src/main/java/com/ggang/be/domain/group/everyGroup/application/EveryGroupServiceImpl.java
  src/main/java/com/ggang/be/domain/group/onceGroup/OnceGroupEntity.java
  src/main/java/com/ggang/be/domain/group/onceGroup/application/OnceGroupServiceImpl.java
  src/main/java/com/ggang/be/domain/userEveryGroup/application/UserEveryGroupServiceImpl.java
  src/main/java/com/ggang/be/domain/userOnceGroup/application/UserOnceGroupServiceImpl.java
Labels: :star: feat

#68 [refactor] 나의 학교명 조회 API Token 검증 추가
  src/main/java/com/ggang/be/api/user/controller/UserController.java
Labels: :factory: refactor

#69 [deploy] #67 yml 파일 서버와 연계하기 위해 Dockerfile 수정 진행
  Dockerfile
Labels: :package: deploy

#72 [fix] 내 강의 시간표 조회 API idx 값 던져주기
  src/main/java/com/ggang/be/api/user/controller/UserController.java
  src/main/java/com/ggang/be/domain/timslot/ReadCommonInvalidTimeVoMaker.java
  src/main/java/com/ggang/be/domain/timslot/vo/ReadCommonInvalidTimeVo.java
Labels: :hammer: fix

#76 [feat] 모임 신청 취소 API 기능 구현
  src/main/java/com/ggang/be/api/facade/GroupFacade.java
  src/main/java/com/ggang/be/api/group/controller/GroupController.java
  src/main/java/com/ggang/be/api/group/everyGroup/service/EveryGroupService.java
  src/main/java/com/ggang/be/api/group/onceGroup/service/OnceGroupService.java
  src/main/java/com/ggang/be/api/userEveryGroup/service/UserEveryGroupService.java
  src/main/java/com/ggang/be/api/userOnceGroup/service/UserOnceGroupService.java
  src/main/java/com/ggang/be/domain/group/everyGroup/EveryGroupEntity.java
  src/main/java/com/ggang/be/domain/group/everyGroup/application/EveryGroupServiceImpl.java
  src/main/java/com/ggang/be/domain/group/onceGroup/OnceGroupEntity.java
  src/main/java/com/ggang/be/domain/group/onceGroup/application/OnceGroupServiceImpl.java
  src/main/java/com/ggang/be/domain/group/onceGroup/infra/OnceGroupRepository.java
  src/main/java/com/ggang/be/domain/userEveryGroup/application/UserEveryGroupServiceImpl.java
  src/main/java/com/ggang/be/domain/userEveryGroup/infra/UserEveryGroupRepository.java
  src/main/java/com/ggang/be/domain/userOnceGroup/application/UserOnceGroupServiceImpl.java
  src/main/java/com/ggang/be/domain/userOnceGroup/infra/UserOnceGroupRepository.java
Labels: :star: feat

#77 [fix] 댓글 조회 API (모임방 / 채우기) → 응답에 status, 공통 응답은 뎁스 줄여서 던져보내는 방식으로 진행, 학교 검증 과정 추가
  src/main/java/com/ggang/be/api/common/ResponseError.java
  src/main/java/com/ggang/be/api/facade/CommentFacade.java
  src/main/java/com/ggang/be/domain/common/SameSchoolValidator.java
  src/main/java/com/ggang/be/domain/group/everyGroup/application/EveryGroupServiceImpl.java
  src/main/java/com/ggang/be/domain/group/everyGroup/vo/ReadEveryGroupCommentCommonVo.java
  src/main/java/com/ggang/be/domain/group/onceGroup/application/OnceGroupServiceImpl.java
  src/main/java/com/ggang/be/domain/group/onceGroup/vo/ReadOnceGroupCommentCommonVo.java
  src/main/java/com/ggang/be/domain/group/vo/GroupCommentVo.java
  src/main/java/com/ggang/be/domain/group/vo/ReadCommentGroup.java
  src/main/java/com/ggang/be/domain/school/SchoolEntity.java
  src/test/java/com/ggang/be/domain/common/SameSchoolValidatorTest.java
  src/test/java/com/ggang/be/domain/group/GroupCommentVoFixture.java
  src/test/java/com/ggang/be/domain/group/everyGroup/EveryGroupFixture.java
  src/test/java/com/ggang/be/domain/group/everyGroup/application/EveryGroupServiceImplTest.java
  src/test/java/com/ggang/be/domain/group/onceGroup/OnceGroupFixture.java
  src/test/java/com/ggang/be/domain/group/onceGroup/application/OnceGroupServiceImplTest.java
  src/test/java/com/ggang/be/domain/school/fixture/SchoolEntityFixture.java
  src/test/java/com/ggang/be/domain/user/fixture/UserEntityFixture.java
Labels: :hammer: fix

#81 [fix] 참여 가능한 모임 조회 조건 수정
  src/main/java/com/ggang/be/domain/timslot/lectureTimeSlot/application/LectureTimeSlotServiceImpl.java
  src/main/java/com/ggang/be/domain/timslot/lectureTimeSlot/infra/LectureTimeSlotRepository.java
Labels: :hammer: fix

#83 [fix] 모임 신청 시 시간표 검증 로직 추가
  src/main/java/com/ggang/be/api/facade/GroupFacade.java
  src/main/java/com/ggang/be/api/group/everyGroup/service/EveryGroupService.java
  src/main/java/com/ggang/be/api/group/onceGroup/service/OnceGroupService.java
  src/main/java/com/ggang/be/domain/group/everyGroup/application/EveryGroupServiceImpl.java
  src/main/java/com/ggang/be/domain/group/onceGroup/application/OnceGroupServiceImpl.java
Labels: :hammer: fix

#84 [feat] 공백채우기 등록하기 API userEveryGroup, userOnceGroup 연계하기!
  src/main/java/com/ggang/be/api/facade/GroupFacade.java
  src/main/java/com/ggang/be/api/group/controller/GroupController.java
  src/main/java/com/ggang/be/api/group/everyGroup/service/EveryGroupService.java
  src/main/java/com/ggang/be/api/group/onceGroup/service/OnceGroupService.java
  src/main/java/com/ggang/be/domain/group/everyGroup/application/EveryGroupServiceImpl.java
  src/main/java/com/ggang/be/domain/group/onceGroup/application/OnceGroupServiceImpl.java
Labels: :star: feat, :hammer: fix

#89 [fix] 소개글 검증 api http method get -> post 로 수정
  src/main/java/com/ggang/be/api/user/controller/UserController.java
Labels: :hammer: fix

#91 [fix] 모임 정보 조회 API Response Body 수정
  src/main/java/com/ggang/be/api/group/dto/GroupResponse.java
  src/main/java/com/ggang/be/api/group/everyGroup/service/EveryGroupService.java
  src/main/java/com/ggang/be/api/mapper/GroupResponseMapper.java
  src/main/java/com/ggang/be/domain/group/everyGroup/application/EveryGroupServiceImpl.java
  src/main/java/com/ggang/be/domain/group/everyGroup/dto/EveryGroupDetail.java
  src/main/java/com/ggang/be/domain/group/everyGroup/dto/EveryGroupDto.java
  src/main/java/com/ggang/be/domain/group/onceGroup/dto/OnceGroupDto.java
  src/main/java/com/ggang/be/domain/timslot/gongbaekTimeSlot/GongbaekTimeSlotEntity.java
  src/test/java/com/ggang/be/domain/group/everyGroup/EveryGroupFixture.java
Labels: :hammer: fix

#99 [fix] 댓글 작성하기, 조회하기 API qa 검증 후 나타난 오류 수정
  src/main/java/com/ggang/be/api/facade/CommentFacade.java
  src/main/java/com/ggang/be/domain/group/vo/GroupCommentVo.java
Labels: :hammer: fix

#100 [fix] 나의 모임 조회 API Response Body 수정
  src/main/java/com/ggang/be/api/facade/GroupFacade.java
  src/main/java/com/ggang/be/api/group/controller/GroupController.java
  src/main/java/com/ggang/be/api/group/dto/MyGroupResponse.java
Labels: :hammer: fix

#107 [deploy] ci/cd 스크립트 작성
  .github/workflows/gongbaek-build-ci.yml
  .github/workflows/gongbaek-cd.yml
  .github/workflows/gongbaek-test-ci.yml
Labels: :package: deploy

#114 [deploy] 여태까지 결과물 배포진행
  .github/workflows/gongbaek-build-ci.yml
  .github/workflows/gongbaek-cd.yml
  .github/workflows/gongbaek-test-ci.yml
  src/main/java/com/ggang/be/Application.java
  src/main/java/com/ggang/be/api/comment/controller/CommentController.java
  src/main/java/com/ggang/be/api/comment/dto/WriteCommentEntityDto.java
  src/main/java/com/ggang/be/api/comment/dto/WriteCommentRequest.java
  src/main/java/com/ggang/be/api/comment/facade/CommentFacade.java
  src/main/java/com/ggang/be/api/comment/facade/EveryGroupCommentStrategyFacade.java
  src/main/java/com/ggang/be/api/comment/facade/OnceGroupCommentStrategyFacade.java
  src/main/java/com/ggang/be/api/comment/registry/CommentStrategy.java
  src/main/java/com/ggang/be/api/comment/registry/CommentStrategyRegistry.java
  src/main/java/com/ggang/be/api/exception/GlobalExceptionHandler.java
  src/main/java/com/ggang/be/api/facade/CommentFacade.java
  src/main/java/com/ggang/be/api/facade/GongbaekRequestFacade.java
  src/main/java/com/ggang/be/api/facade/GroupFacade.java
  src/main/java/com/ggang/be/api/group/GroupStatusUpdater.java
  src/main/java/com/ggang/be/api/group/controller/GroupController.java
  src/main/java/com/ggang/be/api/group/dto/MyGroupResponse.java
  src/main/java/com/ggang/be/api/group/everyGroup/service/EveryGroupService.java
  src/main/java/com/ggang/be/api/group/onceGroup/service/OnceGroupService.java
  src/main/java/com/ggang/be/api/userEveryGroup/service/UserEveryGroupService.java
  src/main/java/com/ggang/be/api/userOnceGroup/service/UserOnceGroupService.java
  src/main/java/com/ggang/be/domain/comment/CommentEntity.java
  src/main/java/com/ggang/be/domain/group/IntroductionValidator.java
  src/main/java/com/ggang/be/domain/group/LocationValidator.java
  src/main/java/com/ggang/be/domain/group/TitleValidator.java
  src/main/java/com/ggang/be/domain/group/everyGroup/EveryGroupEntity.java
  src/main/java/com/ggang/be/domain/group/everyGroup/application/EveryGroupServiceImpl.java
  src/main/java/com/ggang/be/domain/group/everyGroup/infra/EveryGroupRepository.java
  src/main/java/com/ggang/be/domain/group/onceGroup/OnceGroupEntity.java
  src/main/java/com/ggang/be/domain/group/onceGroup/application/OnceGroupServiceImpl.java
  src/main/java/com/ggang/be/domain/group/onceGroup/infra/OnceGroupRepository.java
  src/main/java/com/ggang/be/domain/timslot/gongbaekTimeSlot/GongbaekTimeSlotEntity.java
  src/main/java/com/ggang/be/domain/userEveryGroup/application/UserEveryGroupServiceImpl.java
  src/main/java/com/ggang/be/domain/userEveryGroup/infra/UserEveryGroupRepository.java
  src/main/java/com/ggang/be/domain/userOnceGroup/application/UserOnceGroupServiceImpl.java
  src/main/java/com/ggang/be/domain/userOnceGroup/infra/UserOnceGroupRepository.java
  src/main/java/com/ggang/be/global/annotation/Registry.java
  src/main/java/com/ggang/be/global/annotation/Strategy.java
  src/main/java/com/ggang/be/global/schedule/GroupUpdateScheduler.java
  src/main/java/com/ggang/be/global/schedule/SchedulerConfig.java
  src/main/java/com/ggang/be/global/util/TimeConverter.java
  src/main/java/com/ggang/be/global/util/TimeValidator.java
  src/test/java/com/ggang/be/global/jwt/JwtServiceTest.java
  src/test/java/com/ggang/be/global/util/TimeConverterTest.java
Labels: :package: deploy

#119 [feat] 카테고리 필터링 조회 기능 추가
  src/main/java/com/ggang/be/api/facade/GroupFacade.java
  src/main/java/com/ggang/be/api/group/controller/GroupController.java
  src/main/java/com/ggang/be/api/group/dto/ActiveGroupsResponse.java
  src/main/java/com/ggang/be/api/group/everyGroup/service/EveryGroupService.java
  src/main/java/com/ggang/be/api/group/onceGroup/service/OnceGroupService.java
  src/main/java/com/ggang/be/domain/group/everyGroup/application/EveryGroupServiceImpl.java
  src/main/java/com/ggang/be/domain/group/everyGroup/infra/EveryGroupRepository.java
  src/main/java/com/ggang/be/domain/group/onceGroup/application/OnceGroupServiceImpl.java
  src/main/java/com/ggang/be/domain/group/onceGroup/infra/OnceGroupRepository.java
Labels: :star: feat

#118 [deploy] 배포도중 발견한 문제 확인하고 deploy 스크립트 넣고 실행해보기
  .github/workflows/gongbaek-build-ci.yml
  .github/workflows/gongbaek-cd.yml
  .github/workflows/gongbaek-test-ci.yml
Labels: :package: deploy

#120 [deploy] ls 를 통해 해당 패키지 만들어졌는지 확인
  .github/workflows/gongbaek-cd.yml
Labels: :package: deploy

#121 [deploy] #117 eof를 통해 secret 값 넣는 방식 시도
  .github/workflows/gongbaek-cd.yml
Labels: :package: deploy

#122 Release update to main
  .github/workflows/gongbaek-build-ci.yml
  .github/workflows/gongbaek-cd.yml
  .github/workflows/gongbaek-test-ci.yml
Labels: :computer: chore

#125 [fix] Response Body 에 등록자의 프로필 이미지 추가
  src/main/java/com/ggang/be/api/group/dto/ActiveGroupsResponse.java
  src/main/java/com/ggang/be/domain/group/dto/GroupVo.java
  src/main/java/com/ggang/be/domain/group/everyGroup/dto/EveryGroupVo.java
  src/main/java/com/ggang/be/domain/group/onceGroup/dto/OnceGroupVo.java
Labels: :hammer: fix

#126 [fix] 잘못 변경된 파라미터 네이밍 수정하여 정상적으로 응답할 수 있도록 수정
  src/main/java/com/ggang/be/domain/userEveryGroup/infra/UserEveryGroupRepository.java
Labels: :hammer: fix

#130 [refactor] 참여 가능한 모임 조회 시 ONCE, WEEKLY 분기 클래스 분리
  src/main/java/com/ggang/be/api/group/controller/GroupController.java
  src/main/java/com/ggang/be/api/group/everyGroup/strategy/EveryLatestGroupStrategy.java
  src/main/java/com/ggang/be/api/group/facade/GroupFacade.java
  src/main/java/com/ggang/be/api/group/onceGroup/strategy/OnceLatestGroupStrategy.java
  src/main/java/com/ggang/be/api/group/registry/LatestGroupStrategy.java
  src/main/java/com/ggang/be/api/group/registry/LatestGroupStrategyRegistry.java
Labels: :factory: refactor

#131 [feat] response body 에 유저 닉네임 추가
  src/main/java/com/ggang/be/api/user/controller/UserController.java
  src/main/java/com/ggang/be/api/user/dto/UserSchoolResponseDto.java
  src/main/java/com/ggang/be/domain/user/application/UserServiceImpl.java
  src/main/java/com/ggang/be/domain/user/dto/UserSchoolDto.java
  src/main/java/com/ggang/be/domain/user/infra/UserRepository.java
Labels: :star: feat

#137 [refactor] 모임 신청 API registry, strategy 기반으로 클래스 분리 진행
  src/main/java/com/ggang/be/api/group/everyGroup/strategy/ApplyEveryGroupStrategy.java
  src/main/java/com/ggang/be/api/group/facade/GroupFacade.java
  src/main/java/com/ggang/be/api/group/onceGroup/strategy/ApplyOnceGroupStrategy.java
  src/main/java/com/ggang/be/api/group/registry/ApplyGroupStrategy.java
  src/main/java/com/ggang/be/api/group/registry/ApplyGroupStrategyRegistry.java
Labels: :factory: refactor

#139 [refactor] 모임 신청 취소하기 API 클래스 분리
  src/main/java/com/ggang/be/api/group/everyGroup/strategy/CancelEveryGroupStrategy.java
  src/main/java/com/ggang/be/api/group/facade/GroupFacade.java
  src/main/java/com/ggang/be/api/group/onceGroup/strategy/CancelOnceGroupStrategy.java
  src/main/java/com/ggang/be/api/group/registry/CancelGroupStrategy.java
  src/main/java/com/ggang/be/api/group/registry/CancelGroupStrategyRegistry.java
Labels: :factory: refactor

#143 [refactor] 등록자 프로필 조회 API 클래스 분리
  src/main/java/com/ggang/be/api/group/everyGroup/strategy/EveryGroupUserInfoStrategy.java
  src/main/java/com/ggang/be/api/group/facade/GroupFacade.java
  src/main/java/com/ggang/be/api/group/onceGroup/strategy/OnceGroupUserInfoStrategy.java
  src/main/java/com/ggang/be/api/group/registry/GroupUserInfoStrategy.java
  src/main/java/com/ggang/be/api/group/registry/GroupUserInfoStrategyRegistry.java
Labels: :factory: refactor

#141 [refactor] 모임 등록하기 api registry, strategy 이용해 클래스 분리 진행
  src/main/java/com/ggang/be/api/group/dto/PrepareRegisterInfo.java
  src/main/java/com/ggang/be/api/group/everyGroup/strategy/RegisterEveryGroupStrategy.java
  src/main/java/com/ggang/be/api/group/facade/GroupFacade.java
  src/main/java/com/ggang/be/api/group/facade/PrepareRegisterGongbaekFacade.java
  src/main/java/com/ggang/be/api/group/onceGroup/strategy/RegisterOnceGroupStrategy.java
  src/main/java/com/ggang/be/api/group/registry/RegisterGroupStrategy.java
  src/main/java/com/ggang/be/api/group/registry/RegisterGroupStrategyRegistry.java
Labels: :factory: refactor

#145 [refactor] 나의 모임 전체 조회 API 클래스 분리
  src/main/java/com/ggang/be/api/group/GroupVoAggregator.java
  src/main/java/com/ggang/be/api/group/facade/GroupFacade.java
  src/main/java/com/ggang/be/api/group/registry/MyGroupStrategy.java
  src/main/java/com/ggang/be/api/group/registry/MyGroupStrategyRegistry.java
  src/main/java/com/ggang/be/api/group/registry/RegisterGroupStrategy.java
  src/main/java/com/ggang/be/api/group/strategy/MyApplyGroupStrategy.java
  src/main/java/com/ggang/be/api/group/strategy/MyRegisterGroupStrategy.java
Labels: :factory: refactor

#146 [refactor] 채우기 모임 전체 조회 API 클래스 분리 진행
  src/main/java/com/ggang/be/api/group/ActivceCombinedGroupVoPreparer.java
  src/main/java/com/ggang/be/api/group/dto/CombinedGroupVos.java
  src/main/java/com/ggang/be/api/group/everyGroup/strategy/ApplyEveryGroupStrategy.java
  src/main/java/com/ggang/be/api/group/facade/GroupFacade.java
  src/main/java/com/ggang/be/api/group/onceGroup/strategy/ApplyOnceGroupStrategy.java
  src/main/java/com/ggang/be/api/lectureTimeSlot/service/LectureTimeSlotService.java
  src/main/java/com/ggang/be/domain/timslot/lectureTimeSlot/application/LectureTimeSlotServiceImpl.java
Labels: :factory: refactor

#149 [refactor] 가장 가까운 모임 1개 조회 API 클래스 분리 작업 진행
  src/main/java/com/ggang/be/api/group/ActiveCombinedGroupVoPreparer.java
  src/main/java/com/ggang/be/api/group/CombinedNearestGroupVo.java
  src/main/java/com/ggang/be/api/group/CombinedNearestGroupVoPreparer.java
  src/main/java/com/ggang/be/api/group/everyGroup/strategy/NearestEveryGroupResponseStrategy.java
  src/main/java/com/ggang/be/api/group/facade/GroupFacade.java
  src/main/java/com/ggang/be/api/group/onceGroup/strategy/NearestOnceGroupResponseStrategy.java
  src/main/java/com/ggang/be/api/group/registry/NearestGroupResponseStrategy.java
  src/main/java/com/ggang/be/api/group/registry/NearestGroupResponseStrategyRegistry.java
  src/main/java/com/ggang/be/api/group/strategy/NearestBothGroupResponseStrategy.java
  src/main/java/com/ggang/be/api/group/strategy/NearestEmptyResponseStrategy.java
  src/main/java/com/ggang/be/api/mapper/GroupResponseMapper.java
  src/main/java/com/ggang/be/api/userEveryGroup/service/UserEveryGroupService.java
  src/main/java/com/ggang/be/api/userOnceGroup/service/UserOnceGroupService.java
  src/main/java/com/ggang/be/domain/group/vo/NearestGroup.java
  src/main/java/com/ggang/be/domain/userEveryGroup/application/UserEveryGroupServiceImpl.java
  src/main/java/com/ggang/be/domain/userEveryGroup/dto/NearestEveryGroup.java
  src/main/java/com/ggang/be/domain/userOnceGroup/application/UserOnceGroupServiceImpl.java
  src/main/java/com/ggang/be/domain/userOnceGroup/dto/NearestOnceGroup.java
Labels: :factory: refactor

#154 [feat] api 시작, 종료 로거를 위한 aop 클래스 생성
  build.gradle
  src/main/java/com/ggang/be/global/aop/LoggingAop.java
Labels: :star: feat

#159 [test] 학교 검색 관련 테스트 코드 작성
  src/test/java/com/ggang/be/api/school/SearchSchoolFacadeTest.java
  src/test/java/com/ggang/be/api/school/SearchSchoolMajorFacadeTest.java
Labels: 🚨 test

#162 [fix] 참여 가능한 모임 조회 response body 에 닉네임 추가
  src/main/java/com/ggang/be/api/group/controller/GroupController.java
  src/main/java/com/ggang/be/api/group/dto/LatestResponse.java
  src/main/java/com/ggang/be/api/group/facade/GroupFacade.java
  src/main/java/com/ggang/be/domain/group/dto/GroupVo.java
  src/main/java/com/ggang/be/domain/group/everyGroup/dto/EveryGroupVo.java
  src/main/java/com/ggang/be/domain/group/onceGroup/dto/OnceGroupVo.java
Labels: :hammer: fix

#163 [fix] #160 클라이언트 요구에 맞춰 모임 등록하기 API 수정 진행!
  src/main/java/com/ggang/be/api/facade/GroupRequestFacade.java
  src/main/java/com/ggang/be/api/group/dto/RegisterGongbaekRequest.java
  src/main/java/com/ggang/be/domain/group/dto/RegisterGroupServiceRequest.java
  src/main/java/com/ggang/be/domain/group/everyGroup/application/EveryGroupServiceImpl.java
Labels: :hammer: fix

#164 [deploy] 새롭게 반영된 사항 적용해서 배포합니다
  src/main/java/com/ggang/be/api/facade/GroupRequestFacade.java
  src/main/java/com/ggang/be/api/group/controller/GroupController.java
  src/main/java/com/ggang/be/api/group/dto/LatestResponse.java
  src/main/java/com/ggang/be/api/group/dto/RegisterGongbaekRequest.java
  src/main/java/com/ggang/be/api/group/facade/GroupFacade.java
  src/main/java/com/ggang/be/domain/group/dto/GroupVo.java
  src/main/java/com/ggang/be/domain/group/dto/RegisterGroupServiceRequest.java
  src/main/java/com/ggang/be/domain/group/everyGroup/application/EveryGroupServiceImpl.java
  src/main/java/com/ggang/be/domain/group/everyGroup/dto/EveryGroupVo.java
  src/main/java/com/ggang/be/domain/group/onceGroup/dto/OnceGroupVo.java
  src/test/java/com/ggang/be/api/school/SearchSchoolFacadeTest.java
  src/test/java/com/ggang/be/api/school/SearchSchoolMajorFacadeTest.java
Labels: :package: deploy

#170 [fix] GET 메서드 response body -> parameter 로 변경
  src/main/java/com/ggang/be/api/comment/controller/CommentController.java
  src/main/java/com/ggang/be/api/group/controller/GroupController.java
  src/main/java/com/ggang/be/api/group/facade/GroupFacade.java
Labels: :hammer: fix

#171 [chore] 클라이언트 요구사항 반영 배포
  src/main/java/com/ggang/be/api/comment/controller/CommentController.java
  src/main/java/com/ggang/be/api/group/controller/GroupController.java
  src/main/java/com/ggang/be/api/group/dto/ActiveGroupsResponse.java
  src/main/java/com/ggang/be/api/group/facade/GroupFacade.java
Labels: :computer: chore

#172 [fix] 클라 요구에 따라 api response 필드명 일치 작업 진행 -> weekDate: 날짜, weekDay: 요일
  src/main/java/com/ggang/be/api/facade/TimeTableFacade.java
  src/main/java/com/ggang/be/api/group/dto/ActiveGroupsResponse.java
  src/main/java/com/ggang/be/api/group/dto/GroupResponse.java
  src/main/java/com/ggang/be/api/group/dto/LatestResponse.java
  src/main/java/com/ggang/be/api/group/dto/MyGroupResponse.java
  src/main/java/com/ggang/be/api/group/dto/NearestGroupResponse.java
  src/main/java/com/ggang/be/api/group/dto/RegisterGongbaekRequest.java
  src/main/java/com/ggang/be/api/mapper/GroupResponseMapper.java
  src/main/java/com/ggang/be/api/user/vo/TimeTableVo.java
  src/main/java/com/ggang/be/domain/constant/WeekDay.java
  src/main/java/com/ggang/be/domain/group/dto/GroupVo.java
  src/main/java/com/ggang/be/domain/group/dto/RegisterGroupServiceRequest.java
  src/main/java/com/ggang/be/domain/group/everyGroup/dto/EveryGroupVo.java
  src/main/java/com/ggang/be/domain/group/everyGroup/infra/EveryGroupRepository.java
  src/main/java/com/ggang/be/domain/group/onceGroup/dto/OnceGroupDto.java
  src/main/java/com/ggang/be/domain/group/vo/NearestGroup.java
  src/main/java/com/ggang/be/domain/timslot/ReadCommonInvalidTimeVoMaker.java
  src/main/java/com/ggang/be/domain/timslot/gongbaekTimeSlot/GongbaekTimeSlotEntity.java
  src/main/java/com/ggang/be/domain/timslot/gongbaekTimeSlot/application/GongbaekTimeSlotServiceImpl.java
  src/main/java/com/ggang/be/domain/timslot/gongbaekTimeSlot/dto/GongbaekTimeSlotRequest.java
  src/main/java/com/ggang/be/domain/timslot/lectureTimeSlot/LectureTimeSlotEntity.java
  src/main/java/com/ggang/be/domain/timslot/lectureTimeSlot/application/LectureTimeSlotServiceImpl.java
  src/main/java/com/ggang/be/domain/timslot/lectureTimeSlot/dto/LectureTimeSlotRequest.java
  src/main/java/com/ggang/be/domain/timslot/lectureTimeSlot/infra/LectureTimeSlotRepository.java
  src/main/java/com/ggang/be/domain/timslot/lectureTimeSlot/vo/LectureTimeSlotVo.java
  src/main/java/com/ggang/be/domain/timslot/vo/ReadCommonInvalidTimeVo.java
  src/main/java/com/ggang/be/domain/userEveryGroup/application/UserEveryGroupServiceImpl.java
  src/main/java/com/ggang/be/global/util/TimeValidator.java
  src/test/java/com/ggang/be/domain/gongbaekTImeSlot/GongbaekTimeSlotFixture.java
  src/test/java/com/ggang/be/domain/lectureTimeSlot/application/LectureTimeSlotServiceImplTest.java
  src/test/java/com/ggang/be/domain/lectureTimeSlot/fixture/LectureTimeSlotFixture.java
Labels: :hammer: fix

#175 [fix] 나의 모임 전체 조회 API response body 수정
  src/main/java/com/ggang/be/api/group/controller/GroupController.java
  src/main/java/com/ggang/be/api/group/dto/FinalMyGroupResponse.java
Labels: :hammer: fix

#176 [deploy] 서버에 배포 진행합니다.
  src/main/java/com/ggang/be/api/facade/TimeTableFacade.java
  src/main/java/com/ggang/be/api/group/controller/GroupController.java
  src/main/java/com/ggang/be/api/group/dto/ActiveGroupsResponse.java
  src/main/java/com/ggang/be/api/group/dto/FinalMyGroupResponse.java
  src/main/java/com/ggang/be/api/group/dto/GroupResponse.java
  src/main/java/com/ggang/be/api/group/dto/LatestResponse.java
  src/main/java/com/ggang/be/api/group/dto/MyGroupResponse.java
  src/main/java/com/ggang/be/api/group/dto/NearestGroupResponse.java
  src/main/java/com/ggang/be/api/group/dto/RegisterGongbaekRequest.java
  src/main/java/com/ggang/be/api/mapper/GroupResponseMapper.java
  src/main/java/com/ggang/be/api/user/vo/TimeTableVo.java
  src/main/java/com/ggang/be/domain/constant/WeekDay.java
  src/main/java/com/ggang/be/domain/group/dto/GroupVo.java
  src/main/java/com/ggang/be/domain/group/dto/RegisterGroupServiceRequest.java
  src/main/java/com/ggang/be/domain/group/everyGroup/dto/EveryGroupVo.java
  src/main/java/com/ggang/be/domain/group/everyGroup/infra/EveryGroupRepository.java
  src/main/java/com/ggang/be/domain/group/onceGroup/dto/OnceGroupDto.java
  src/main/java/com/ggang/be/domain/group/vo/NearestGroup.java
  src/main/java/com/ggang/be/domain/timslot/ReadCommonInvalidTimeVoMaker.java
  src/main/java/com/ggang/be/domain/timslot/gongbaekTimeSlot/GongbaekTimeSlotEntity.java
  src/main/java/com/ggang/be/domain/timslot/gongbaekTimeSlot/application/GongbaekTimeSlotServiceImpl.java
  src/main/java/com/ggang/be/domain/timslot/gongbaekTimeSlot/dto/GongbaekTimeSlotRequest.java
  src/main/java/com/ggang/be/domain/timslot/lectureTimeSlot/LectureTimeSlotEntity.java
  src/main/java/com/ggang/be/domain/timslot/lectureTimeSlot/application/LectureTimeSlotServiceImpl.java
  src/main/java/com/ggang/be/domain/timslot/lectureTimeSlot/dto/LectureTimeSlotRequest.java
  src/main/java/com/ggang/be/domain/timslot/lectureTimeSlot/infra/LectureTimeSlotRepository.java
  src/main/java/com/ggang/be/domain/timslot/lectureTimeSlot/vo/LectureTimeSlotVo.java
  src/main/java/com/ggang/be/domain/timslot/vo/ReadCommonInvalidTimeVo.java
  src/main/java/com/ggang/be/domain/userEveryGroup/application/UserEveryGroupServiceImpl.java
  src/main/java/com/ggang/be/global/util/TimeValidator.java
  src/test/java/com/ggang/be/domain/gongbaekTImeSlot/GongbaekTimeSlotFixture.java
  src/test/java/com/ggang/be/domain/lectureTimeSlot/application/LectureTimeSlotServiceImplTest.java
  src/test/java/com/ggang/be/domain/lectureTimeSlot/fixture/LectureTimeSlotFixture.java
Labels: :package: deploy

#178 [feat] 나의 모임 삭제하기 API 기능 구현
  src/main/java/com/ggang/be/api/group/controller/GroupController.java
  src/main/java/com/ggang/be/api/group/everyGroup/service/EveryGroupService.java
  src/main/java/com/ggang/be/api/group/everyGroup/strategy/DeleteEveryGroupStrategy.java
  src/main/java/com/ggang/be/api/group/facade/GroupFacade.java
  src/main/java/com/ggang/be/api/group/onceGroup/service/OnceGroupService.java
  src/main/java/com/ggang/be/api/group/onceGroup/strategy/DeleteOnceGroupStrategy.java
  src/main/java/com/ggang/be/api/group/registry/DeleteGroupStrategy.java
  src/main/java/com/ggang/be/api/group/registry/DeleteGroupStrategyRegistry.java
  src/main/java/com/ggang/be/domain/group/everyGroup/application/EveryGroupServiceImpl.java
  src/main/java/com/ggang/be/domain/group/onceGroup/application/OnceGroupServiceImpl.java
Labels: :star: feat

#182 [fix] #181 장소 검증 조건 변경에 따른 수정 진행
  src/main/java/com/ggang/be/domain/group/LocationValidator.java
Labels: :hammer: fix

#183 [deploy] 클라이언트 요구사항 반영 후 배포 진행합니다.
  src/main/java/com/ggang/be/api/group/controller/GroupController.java
  src/main/java/com/ggang/be/api/group/everyGroup/service/EveryGroupService.java
  src/main/java/com/ggang/be/api/group/everyGroup/strategy/DeleteEveryGroupStrategy.java
  src/main/java/com/ggang/be/api/group/facade/GroupFacade.java
  src/main/java/com/ggang/be/api/group/onceGroup/service/OnceGroupService.java
  src/main/java/com/ggang/be/api/group/onceGroup/strategy/DeleteOnceGroupStrategy.java
  src/main/java/com/ggang/be/api/group/registry/DeleteGroupStrategy.java
  src/main/java/com/ggang/be/api/group/registry/DeleteGroupStrategyRegistry.java
  src/main/java/com/ggang/be/domain/group/LocationValidator.java
  src/main/java/com/ggang/be/domain/group/everyGroup/application/EveryGroupServiceImpl.java
  src/main/java/com/ggang/be/domain/group/onceGroup/application/OnceGroupServiceImpl.java
Labels: :package: deploy

#186 [hotfix] 회원가입 진행 시 빠진 검증 기능 추가
  src/main/java/com/ggang/be/api/facade/GroupRequestFacade.java
  src/main/java/com/ggang/be/api/facade/SignupFacade.java
  src/main/java/com/ggang/be/api/facade/SignupRequestFacade.java
  src/main/java/com/ggang/be/api/user/NicknameValidator.java
  src/main/java/com/ggang/be/api/user/controller/UserController.java
  src/main/java/com/ggang/be/api/user/vo/TimeTableVo.java
  src/main/java/com/ggang/be/domain/group/IntroductionValidator.java
  src/main/java/com/ggang/be/global/util/TimeValidator.java
  src/test/java/com/ggang/be/api/user/NicknameValidatorTest.java
Labels: :hammer: fix

#187 [docs] read.me 파일 수정
  README.md
Labels: :memo: docs

#188 [deploy] 배포 진행합니다!
  README.md
  src/main/java/com/ggang/be/api/facade/GroupRequestFacade.java
  src/main/java/com/ggang/be/api/facade/SignupFacade.java
  src/main/java/com/ggang/be/api/facade/SignupRequestFacade.java
  src/main/java/com/ggang/be/api/user/NicknameValidator.java
  src/main/java/com/ggang/be/api/user/controller/UserController.java
  src/main/java/com/ggang/be/api/user/vo/TimeTableVo.java
  src/main/java/com/ggang/be/domain/group/IntroductionValidator.java
  src/main/java/com/ggang/be/global/util/TimeValidator.java
  src/test/java/com/ggang/be/api/user/NicknameValidatorTest.java
Labels: :package: deploy
